#!/bin/sh

# Loading Hydra commons script
. git-hydra-rules
. git-hydra-commons

usage() {
    echo
}

main() {
    if is_tutorial $@; then
        usage
    else
        require_git_repo
        require_hydra_template

        local parameters=$@
        local command=$1; shift
        local action=$1; shift
        cp /d/scm/git/github/victoraugustofd/githydra/templates/hydra.json .
        template=$(read_template "hydra.json")

        rm hydra.json

        validate_command $command
        validate_action $command $action

        fire_rules $parameters
    fi
}

main $@
